# Generated by Django 4.2.7 on 2023-11-06 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField(blank=True, default=0.0, editable=False, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='product-pic')),
                ('product_type', models.CharField(max_length=50)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='belongs', to='product.brand')),
            ],
        ),
    ]
