# Generated by Django 4.2.7 on 2023-11-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('vermifuga', 'Vermifuga'), ('Adubo', 'Adubo'), ('Veneno', 'Veneno')], max_length=50),
        ),
    ]
