# Generated by Django 4.2.6 on 2023-12-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('vermifuga', 'Vermifuga'), ('Adubo', 'Adubo'), ('Veneno', 'Veneno'), ('Fertilizante', 'Fertilizante'), ('Agrotoxico', 'Agrotoxico')], max_length=50),
        ),
    ]
