# Generated by Django 4.2.6 on 2023-12-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_brand_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='picture',
            field=models.ImageField(blank=True, upload_to='brand-pic'),
        ),
    ]
