# Generated by Django 4.2.6 on 2023-12-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('vermifuga', 'Vermifuga'), ('Adubo', 'Adubo'), ('Veneno', 'Veneno'), ('Fertilizante', 'Fertilizante'), ('Agrotoxico', 'Agrotoxico'), ('Fungicida', 'Fungicida')], max_length=50),
        ),
    ]
